# Generated by Django 6.0.6 on 2026-06-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('kind', models.CharField(max_length=32)),
                ('schema_version', models.CharField(max_length=16)),
                ('raw', models.JSONField()),
                ('effects', models.JSONField(default=list)),
                ('capabilities', models.JSONField(default=list)),
                ('intent_tags', models.JSONField(default=list)),
                ('name_hints', models.JSONField(default=list)),
                ('terminates', models.CharField(blank=True, max_length=16, null=True)),
                ('complexity', models.CharField(blank=True, max_length=64, null=True)),
                ('type_str', models.TextField(blank=True, null=True)),
                ('body_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['kind'], name='commons_rec_kind_48f17e_idx'), models.Index(fields=['terminates'], name='commons_rec_termina_14d734_idx')],
            },
        ),
    ]
