# Generated by Django 6.0.6 on 2026-06-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
