# Generated by Django 6.0.7 on 2026-07-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0005_certification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='blob_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='blob_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
