# Generated by Django 6.0.7 on 2026-07-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_record_blob_bytes_record_blob_sha256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('root', models.CharField(max_length=80)),
                ('count', models.IntegerField()),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
