# Generated by Django 6.0.7 on 2026-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0007_anchor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=120)),
                ('root', models.CharField(max_length=80)),
                ('agreement', models.CharField(max_length=16)),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
